var localNotificationsModel = {
    MT_NOTES: [
        {
            QMNUM: "000010000408",
            INSTID_A: "000010000408",
            INSTID_B: "FOL42000000000004RAW49000000007894",
            CRDAT: "20241119",
            CRTIM: "171138",
            DOCDES: "Note by GTM - 20241119",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000441  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000408",
            INSTID_A: "000010000408",
            INSTID_B: "FOL42000000000004RAW49000000007893",
            CRDAT: "20241119",
            CRTIM: "171030",
            DOCDES: "Note by GTM - 20241119",
            FILE_EXT: "TXT",
            CONTENT: "\\r\\nAdd new Message for Demo",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000407",
            INSTID_A: "000010000407",
            INSTID_B: "FOL42000000000004RAW49000000007891",
            CRDAT: "20241119",
            CRTIM: "165124",
            DOCDES: "Note by GTM - 20241119",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000440  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000407",
            INSTID_A: "000010000407",
            INSTID_B: "FOL42000000000004RAW49000000007890",
            CRDAT: "20241119",
            CRTIM: "165035",
            DOCDES: "Note by GTM - 20241119",
            FILE_EXT: "TXT",
            CONTENT: "\\r\\nAdd Message",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000406",
            INSTID_A: "000010000406",
            INSTID_B: "FOL42000000000004RAW49000000007872",
            CRDAT: "20241118",
            CRTIM: "230517",
            DOCDES: "Note by GTM - 20241118",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000439  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000405",
            INSTID_A: "000010000405",
            INSTID_B: "FOL42000000000004RAW49000000007868",
            CRDAT: "20241118",
            CRTIM: "210041",
            DOCDES: "Note by GTM - 20241118",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000438  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000405",
            INSTID_A: "000010000405",
            INSTID_B: "FOL42000000000004RAW49000000007867",
            CRDAT: "20241118",
            CRTIM: "205804",
            DOCDES: "Note by GTM - 20241118",
            FILE_EXT: "TXT",
            CONTENT: "\\r\\nPlease elaborate.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000405",
            INSTID_A: "000010000405",
            INSTID_B: "FOL42000000000004RAW49000000007866",
            CRDAT: "20241118",
            CRTIM: "205624",
            DOCDES: "Note by GTM - 20241118",
            FILE_EXT: "TXT",
            CONTENT: "\\r\\nNew Message Assigned to Notification",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000399",
            INSTID_A: "000010000399",
            INSTID_B: "FOL42000000000004RAW49000000007614",
            CRDAT: "20241108",
            CRTIM: "135252",
            DOCDES: "Note by GTM - 20241108",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000432  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000337",
            INSTID_A: "000010000337",
            INSTID_B: "FOL42000000000004RAW49000000006381",
            CRDAT: "20240919",
            CRTIM: "110237",
            DOCDES: "Note by GTM - 20240919",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000410  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000335",
            INSTID_A: "000010000335",
            INSTID_B: "FOL42000000000004RAW49000000006352",
            CRDAT: "20240918",
            CRTIM: "103454",
            DOCDES: "Note by GTM - 20240918",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000406  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000327",
            INSTID_A: "000010000327",
            INSTID_B: "FOL42000000000004RAW49000000006007",
            CRDAT: "20240904",
            CRTIM: "145645",
            DOCDES: "Note by GTM - 20240904",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000401  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000288",
            INSTID_A: "000010000288",
            INSTID_B: "FOL42000000000004RAW49000000002956",
            CRDAT: "20240502",
            CRTIM: "102700",
            DOCDES: "Note by GTM - 20240502",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000373  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000240",
            INSTID_A: "000010000240",
            INSTID_B: "FOL42000000000004RAW49000000002716",
            CRDAT: "20240422",
            CRTIM: "110751",
            DOCDES: "Note by GARDUK - 20240422",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000371  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-solid/user-shield",
            HIGHLIGHT: "",
            USER: "Hans Gruber",
            USERNAME: "GARDUK",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000248",
            INSTID_A: "000010000248",
            INSTID_B: "FOL42000000000004RAW49000000001772",
            CRDAT: "20240314",
            CRTIM: "091904",
            DOCDES: "Note by GTM - 20240314",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000367  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
        {
            QMNUM: "000010000246",
            INSTID_A: "000010000246",
            INSTID_B: "FOL42000000000004RAW48000000006009",
            CRDAT: "20230907",
            CRTIM: "122837",
            DOCDES: "Note by GTM - 20230907",
            FILE_EXT: "TXT",
            CONTENT:
                "\\r\\nAutomated message: Work Order 4000327  has been created for this notification.",
            ACTION: "",
            ICON: "sap-icon://fa-regular/user",
            HIGHLIGHT: "",
            USER: "Brad Baker",
            USERNAME: "GTM",
            ID: "00000000000000000000000000000000",
        },
    ],
    MT_NOTIFICATIONS: [
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000210100086",
            FUNCT_LOC: "1010-CWS-CTW-CTW01-CTFN",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Second Malfunction",
            PRIORITY: "3",
            DESSTDATE: "20230906",
            DESSTTIME: "105255",
            DESENDDATE: "20230910",
            DESENDTM: "105255",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "",
            BREAKDOWN: "",
            STRMLFNDATE: "20230905",
            STRMLFNTIME: "105255",
            REPORTEDBY: "",
            NOTIF_DATE: "20230905",
            NOTIFTIME: "105255",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1010",
            MAINTLOC: "YB_1007",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "Information",
            ICON: "sap-icon://notification-2",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000240",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Cooling Tower Fan Gear Box",
            FLOC_DESC: "Cooling Tower Fan",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "X05. September 2023 12:53 (GTM)\\r\\nSecond Malfunction\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000210100086",
            FUNCT_LOC: "1010-CWS-CTW-CTW01-CTFN",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Technical malfunction 4",
            PRIORITY: "1",
            DESSTDATE: "20230907",
            DESSTTIME: "100609",
            DESENDDATE: "20230908",
            DESENDTM: "100609",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "",
            BREAKDOWN: "",
            STRMLFNDATE: "20230907",
            STRMLFNTIME: "100609",
            REPORTEDBY: "",
            NOTIF_DATE: "20230907",
            NOTIFTIME: "100609",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1010",
            MAINTLOC: "YB_1007",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000246",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Cooling Tower Fan Gear Box",
            FLOC_DESC: "Cooling Tower Fan",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT:
                "X07. September 2023 12:06 (GTM)\\r\\nTechnical Malfunction that needs to be fixed\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000210100086",
            FUNCT_LOC: "1010-CWS-CTW-CTW01-CTFN",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Technical malfunction",
            PRIORITY: "3",
            DESSTDATE: "20230908",
            DESSTTIME: "105409",
            DESENDDATE: "20230912",
            DESENDTM: "105409",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "",
            BREAKDOWN: "",
            STRMLFNDATE: "20230907",
            STRMLFNTIME: "105409",
            REPORTEDBY: "",
            NOTIF_DATE: "20230907",
            NOTIFTIME: "105409",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1010",
            MAINTLOC: "YB_1007",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000248",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Cooling Tower Fan Gear Box",
            FLOC_DESC: "Cooling Tower Fan",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "X07. September 2023 12:54 (GTM)\\r\\nhello there another one\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000217100085",
            FUNCT_LOC: "1710-CWS-CTW-CTW01-CTFN",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Test Notification",
            PRIORITY: "2",
            DESSTDATE: "20240502",
            DESSTTIME: "082523",
            DESENDDATE: "20240504",
            DESENDTM: "082523",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "920",
            BREAKDOWN: "",
            STRMLFNDATE: "20240502",
            STRMLFNTIME: "082523",
            REPORTEDBY: "",
            NOTIF_DATE: "20240502",
            NOTIFTIME: "082523",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1710",
            MAINTLOC: "YB_1707",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000288",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Cooling Tower Fan",
            FLOC_DESC: "Cooling Tower Fan",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "07. September 2023 12:54 (GTM)\\r\\nhello there another one\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "",
            FUNCT_LOC: "1010-CWS-CTW-CTW02",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "test",
            PRIORITY: "3",
            DESSTDATE: "20240828",
            DESSTTIME: "145616",
            DESENDDATE: "20240901",
            DESENDTM: "145616",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "",
            BREAKDOWN: "",
            STRMLFNDATE: "20240827",
            STRMLFNTIME: "145616",
            REPORTEDBY: "",
            NOTIF_DATE: "20240827",
            NOTIFTIME: "145616",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1010",
            MAINTLOC: "YB_1006",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000320",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "",
            FLOC_DESC: "Cooling Tower#02",
            PHASE: "1",
            STATUS_TEXT: "Outstanding",
            LONG_TEXT: "07. September 2023 12:54 (GTM)\\r\\nhello there another one\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000210100085",
            FUNCT_LOC: "1010-CWS-CTW-CTW01-CTFN",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "AC broken",
            PRIORITY: "3",
            DESSTDATE: "20240905",
            DESSTTIME: "125625",
            DESENDDATE: "20240909",
            DESENDTM: "125625",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "",
            BREAKDOWN: "",
            STRMLFNDATE: "20240904",
            STRMLFNTIME: "125625",
            REPORTEDBY: "",
            NOTIF_DATE: "20240904",
            NOTIFTIME: "125625",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1010",
            MAINTLOC: "YB_1007",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000327",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Cooling Tower Fan",
            FLOC_DESC: "Cooling Tower Fan",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "X04. September 2024 14:56 (GTM)\\r\\nFix now pls!\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000210100063",
            FUNCT_LOC: "1010-SPA-SAC-PLAR4-CGB1",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "This is not working",
            PRIORITY: "1",
            DESSTDATE: "20240918",
            DESSTTIME: "083357",
            DESENDDATE: "20240919",
            DESENDTM: "083357",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "",
            BREAKDOWN: "",
            STRMLFNDATE: "20240918",
            STRMLFNTIME: "083357",
            REPORTEDBY: "",
            NOTIF_DATE: "20240918",
            NOTIFTIME: "083357",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1010",
            MAINTLOC: "YB_1004",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000335",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Gear Box",
            FLOC_DESC: "Compr4 - Gear Box",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "X18. September 2024 10:33 (GTM)\\r\\nplease just fix it\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000210100049",
            FUNCT_LOC: "1010-SPA-SAC-PLAR3-CLR1",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Test 2",
            PRIORITY: "3",
            DESSTDATE: "20240920",
            DESSTTIME: "085956",
            DESENDDATE: "20240924",
            DESENDTM: "085956",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "",
            BREAKDOWN: "",
            STRMLFNDATE: "20240919",
            STRMLFNTIME: "085956",
            REPORTEDBY: "",
            NOTIF_DATE: "20240919",
            NOTIFTIME: "085956",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1010",
            MAINTLOC: "YB_1003",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000337",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Compressor Stage 1 cooler",
            FLOC_DESC: "Compr3 - Air Cooler 1",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "X19. September 2024 10:59 (GTM)\\r\\naaa\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000217100065",
            FUNCT_LOC: "1710-SPA-SAC-PLAR4-DSBA",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Breakdown",
            PRIORITY: "1",
            DESSTDATE: "20241108",
            DESSTTIME: "125131",
            DESENDDATE: "20241109",
            DESENDTM: "125131",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "920",
            BREAKDOWN: "",
            STRMLFNDATE: "20241110",
            STRMLFNTIME: "205708",
            REPORTEDBY: "",
            NOTIF_DATE: "20241108",
            NOTIFTIME: "125131",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1710",
            MAINTLOC: "YB_1704",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000399",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "DE side Bearing Assembly",
            FLOC_DESC: "Compr4 - DE side Bearing Assembly",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "X08. November 2024 13:51 (GTM)\\r\\nPlease fix asap\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000217100086",
            FUNCT_LOC: "1710-CWS-CTW-CTW01-CTFN",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Another breakdown",
            PRIORITY: "3",
            DESSTDATE: "20241111",
            DESSTTIME: "214054",
            DESENDDATE: "20241115",
            DESENDTM: "214054",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "920",
            BREAKDOWN: "",
            STRMLFNDATE: "20241110",
            STRMLFNTIME: "214243",
            REPORTEDBY: "",
            NOTIF_DATE: "20241110",
            NOTIFTIME: "214054",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1710",
            MAINTLOC: "YB_1707",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000400",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Cooling Tower Fan Gear Box",
            FLOC_DESC: "Cooling Tower Fan",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "08. November 2024 13:51 (GTM)\\r\\nPlease fix asap\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000217100085",
            FUNCT_LOC: "1710-CWS-CTW-CTW01-CTFN",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Broken Fan",
            PRIORITY: "2",
            DESSTDATE: "20241118",
            DESSTTIME: "195558",
            DESENDDATE: "20241120",
            DESENDTM: "195558",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "920",
            BREAKDOWN: "",
            STRMLFNDATE: "00000000",
            STRMLFNTIME: "000000",
            REPORTEDBY: "",
            NOTIF_DATE: "20241118",
            NOTIFTIME: "195558",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1710",
            MAINTLOC: "YB_1707",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000405",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Cooling Tower Fan",
            FLOC_DESC: "Cooling Tower Fan",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT:
                "X18. November 2024 20:55 (GTM)\\r\\nFan not spinning.  Check capacitor.\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000217100081",
            FUNCT_LOC: "1710-SPA-ADR-DRY01-D1IV",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Electricity not being supplied",
            PRIORITY: "3",
            DESSTDATE: "20241119",
            DESSTTIME: "220345",
            DESENDDATE: "20241123",
            DESENDTM: "220345",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "920",
            BREAKDOWN: "",
            STRMLFNDATE: "20241118",
            STRMLFNTIME: "220345",
            REPORTEDBY: "",
            NOTIF_DATE: "20241118",
            NOTIFTIME: "220345",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1710",
            MAINTLOC: "YB_1705",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000406",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Dryer Inlet Valve",
            FLOC_DESC: "Inlet Valve",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "X18. November 2024 23:03 (GTM)\\r\\nProblem with AC connection\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000217100086",
            FUNCT_LOC: "1710-CWS-CTW-CTW01-CTFN",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Ventilator Blocked",
            PRIORITY: "2",
            DESSTDATE: "20241119",
            DESSTTIME: "154926",
            DESENDDATE: "20241121",
            DESENDTM: "154926",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "920",
            BREAKDOWN: "",
            STRMLFNDATE: "00000000",
            STRMLFNTIME: "000000",
            REPORTEDBY: "",
            NOTIF_DATE: "20241119",
            NOTIFTIME: "154926",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1710",
            MAINTLOC: "YB_1707",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000407",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Cooling Tower Fan Gear Box",
            FLOC_DESC: "Cooling Tower Fan",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "X19. November 2024 16:49 (GTM)\\r\\nVentilator Blocked\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
        {
            REFOBJECTTYPE: "",
            REFOBJECTKEY: "",
            REFRELTYPE: "",
            EQUIPMENT: "000000000217100086",
            FUNCT_LOC: "1710-CWS-CTW-CTW01-CTFN",
            ASSEMBLY: "",
            SERIALNO: "",
            MATERIAL: "",
            DIVISION: "",
            SALES_ORG: "",
            DISTR_CHAN: "",
            SALES_OFFICE: "",
            SALES_GRP: "",
            SHORT_TEXT: "Ventilator Broken",
            PRIORITY: "2",
            DESSTDATE: "20241119",
            DESSTTIME: "160944",
            DESENDDATE: "20241121",
            DESENDTM: "160944",
            DEVICEDATA: "",
            PM_WKCTR: 10000027,
            PURCH_NO_C: "",
            PURCH_DATE: "00000000",
            PLANPLANT: "1710",
            PLANGROUP: "920",
            BREAKDOWN: "",
            STRMLFNDATE: "00000000",
            STRMLFNTIME: "000000",
            REPORTEDBY: "",
            NOTIF_DATE: "20241119",
            NOTIFTIME: "160944",
            CODE_GROUP: "",
            CODING: "",
            DOC_NUMBER: "",
            ITM_NUMBER: 0,
            ENDMLFNDATE: "00000000",
            ENDMLFNTIME: "000000",
            SCENARIO: "",
            ASSEMBLY_EXTERNAL: "",
            ASSEMBLY_GUID: "",
            ASSEMBLY_VERSION: "",
            MATERIAL_EXTERNAL: "",
            MATERIAL_GUID: "",
            MATERIAL_VERSION: "",
            MAINTPLANT: "1710",
            MAINTLOC: "YB_1707",
            MAINTROOM: "",
            START_POINT: "",
            END_POINT: "",
            LINEAR_LENGTH: "",
            LINEAR_UNIT: "",
            LINEAR_UNIT_ISO: "",
            FIRST_OFFSET_TYPE_CODE: "",
            FIRST_OFFSET_VALUE: "",
            FIRST_OFFSET_UNIT: "",
            FIRST_OFFSET_UNIT_ISO: "",
            SECOND_OFFSET_TYPE_CODE: "",
            SECOND_OFFSET_VALUE: "",
            SECOND_OFFSET_UNIT: "",
            SECOND_OFFSET_UNIT_ISO: "",
            MARKER_START_POINT: "",
            MARKER_DISTANCE_START_POINT: "",
            MARKER_END_POINT: "",
            MARKER_DISTANCE_END_POINT: "",
            MARKER_DISTANCE_UNIT: "",
            MARKER_DISTANCE_UNIT_ISO: "",
            SORTFIELD: "",
            EFFECT: "",
            ASSEMBLY_LONG: "",
            MATERIAL_LONG: "",
            REVISION_PM_CS: "",
            LACD_DATE: "00000000",
            OLD_LACD_DATE: "00000000",
            DETECTIONCATALOG: "",
            DETECTIONCODEGROUP: "",
            DETECTIONCODE: "",
            NOTIFREJECTIONREASONCODE: "",
            REF_EXT: "",
            HIGHLIGHT: "None",
            ICON: "sap-icon://notification",
            TPLNR: "",
            QMART: "",
            QMNUM: "000010000408",
            QMTXT: "",
            MALFUNCTION: true,
            BRKDOWN: false,
            EQUIP_DESC: "Cooling Tower Fan Gear Box",
            FLOC_DESC: "Cooling Tower Fan",
            PHASE: "3",
            STATUS_TEXT: "In Process",
            LONG_TEXT: "X19. November 2024 17:09 (GTM)\\r\\nVentilator Broken\\r\\n",
            NEW_MESSAGE: false,
            ID: "00000000000000000000000000000000",
        },
    ],
};

var localInitialize = {
    MT_PRIORITIES: [
        { SPRAS: "E", ARTPR: "PM", PRIOK: "1", PRIOKX: "Very High" },
        { SPRAS: "E", ARTPR: "PM", PRIOK: "2", PRIOKX: "High" },
        { SPRAS: "E", ARTPR: "PM", PRIOK: "3", PRIOKX: "Medium" },
        { SPRAS: "E", ARTPR: "PM", PRIOK: "4", PRIOKX: "Low" },
    ],
    MT_STATUS: [
        {
            DOMNAME: "",
            VALPOS: 0,
            DDLANGUAGE: "",
            DOMVALUE_L: "        0",
            DOMVALUE_H: "",
            DDTEXT: "All",
            DOMVAL_LD: "",
            DOMVAL_HD: "",
            APPVAL: "",
        },
        {
            DOMNAME: "QM_PHASE",
            VALPOS: 1,
            DDLANGUAGE: "E",
            DOMVALUE_L: "1",
            DOMVALUE_H: "",
            DDTEXT: "Outstanding",
            DOMVAL_LD: "",
            DOMVAL_HD: "",
            APPVAL: "",
        },
        {
            DOMNAME: "QM_PHASE",
            VALPOS: 2,
            DDLANGUAGE: "E",
            DOMVALUE_L: "2",
            DOMVALUE_H: "",
            DDTEXT: "Postponed",
            DOMVAL_LD: "",
            DOMVAL_HD: "",
            APPVAL: "",
        },
        {
            DOMNAME: "QM_PHASE",
            VALPOS: 3,
            DDLANGUAGE: "E",
            DOMVALUE_L: "3",
            DOMVALUE_H: "",
            DDTEXT: "In Process",
            DOMVAL_LD: "",
            DOMVAL_HD: "",
            APPVAL: "",
        },
    ],
};
