<div>
    <!-- <div class="sl-embed"> -->
        <iframe loading="lazy" class="sl-demo" src="https://app.storylane.io/share/xox45uy1bldy"
            style="position:absolute;top:0;left:0;width:100%!important;height:100%!important;border:1px solid rgba(63,95,172,0.35);box-shadow: 0px 0px 18px rgba(26, 19, 72, 0.15);border-radius:10px;box-sizing:border-box;"></iframe>
    <!-- </div> -->
</div>